title: DN Institute
tagline: AI-Powered Market Intelligence 🌰
description: >-
  Research and analysis of digital assets, markets, and regulations
baseurl: ""
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-assets

# Collections
collections:
    output: true
  research:
    output: true
  market-intelligence:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "market-intelligence"
    values:
      layout: "market-intelligence"