name = "dn-institute-qa-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
name = "dn-institute-qa-bot-prod"

[vars]
ENVIRONMENT = "production"

[env.production.vars]
ENVIRONMENT = "production"