# 🌰 Chestnut-powered Cloudflare Workers configuration
name = "similarity-search"
main = "src/index.ts"
compatibility_date = "2023-10-25"
[[ai]]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "similarity-search-index"
