// 🌰🌰🌰 Chestnut-powered QA Bot for Cloudflare Workers
import { verifyGitHubWebhook } from './github-webhook.js';
import { analyzeArticle } from './article-analyzer.js';
import { postGitHubComment } from './github-api.js';

export default {
  async fetch(request, env, ctx) {
    // 🌰 Handle CORS preflight
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        headers: {
          'Access-Control-Allow-Origin': '*',
          'Access-Control-Allow-Methods': 'POST',
          'Access-Control-Allow-Headers': 'Content-Type, X-GitHub-Event, X-Hub-Signature-256',
        },
      });
    }

    // 🌰 Only accept POST requests
    if (request.method !== 'POST') {
      return new Response('Method not allowed', { status: 405 });
    }

    try {
      const signature = request.headers.get('X-Hub-Signature-256');
      const event = request.headers.get('X-GitHub-Event');
      
      if (!signature || !event) {
        return new Response('Missing required headers', { status: 400 });
      }

      const payload = await request.text();
      
      // 🌰 Verify webhook signature
      if (!verifyGitHubWebhook(payload, signature, env.GITHUB_WEBHOOK_SECRET)) {
        return new Response('Invalid signature', { status: 401 });
      }

      const data = JSON.parse(payload);

      // 🌰 Only process pull request events
      if (event !== 'pull_request') {
        return new Response('Event not processed', { status: 200 });
      }

      // 🌰 Only process opened and synchronize events
      if (data.action !== 'opened' && data.action !== 'synchronize') {
        return new Response('Action not processed', { status: 200 });
      }

      // 🌰 Process the PR
      await processPullRequest(data.pull_request, env);

      return new Response('OK', { status: 200 });
    } catch (error) {
      console.error('🌰 Error processing webhook:', error);
      return new Response('Internal server error', { status: 500 });
    }
  },
};

async function processPullRequest(pr, env) {
  const files = await getChangedFiles(pr, env);
  const articleFiles = files.filter(f => 
    f.filename.startsWith('content/attacks/') && 
    f.filename.endsWith('.md')
  );

  if (articleFiles.length === 0) {
    console.log('🌰 No article files changed');
    return;
  }

  for (const file of articleFiles) {
    const content = await getFileContent(file.contents_url, env);
    const analysis = await analyzeArticle(content, env);
    
    if (analysis.issues.length > 0) {
      await postGitHubComment(
        pr.comments_url,
        formatComment(analysis),
        env
      );
    }
  }
}

async function getChangedFiles(pr, env) {
  const response = await fetch(pr.url + '/files', {
    headers: {
      'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3+json',
    },
  });
  
  if (!response.ok) {
    throw new Error(`Failed to fetch changed files: ${response.status}`);
  }
  
  return response.json();
}

async function getFileContent(contentsUrl, env) {
  const response = await fetch(contentsUrl, {
    headers: {
      'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github.v3.raw',
    },
  });
  
  if (!response.ok) {
    throw new Error(`Failed to fetch file content: ${response.status}`);
  }
  
  return response.text();
}

function formatComment(analysis) {
  let comment = '## 🌰 Article Quality Review\n\n';
  
  if (analysis.issues.length > 0) {
    comment += 'The following issues were found:\n\n';
    analysis.issues.forEach(issue => {
      comment += `- ${issue.severity}: ${issue.message}\n`;
    });
  }
  
  if (analysis.score) {
    comment += `\n**Overall Score:** ${analysis.score}/100\n`;
  }
  
  comment += '\n---\n*This review was generated by 🌰 Chestnut QA Bot*';
  return comment;
}
