  baseURL = "https://dn.institute/market-health-reporter/"
  languageCode = "en-us"
  title = "Market Health Reporter"
  theme = "hugo-theme-bootstrap"

[params]
  description = "Automated reports with metrics spikes and their interpretation using Market Health API."