name = "worker-article-checker"
main = "src/worker.js"
compatibility_date = "2024-05-29"
workers_dev = true

kv_namespaces = [
  { binding = "checkerPrompts", id = "" }
]

[vars]
OPENAI_API_KEY = ""
BRAVE_API_KEY = ""
LLM_ENDPOINT = "https://api.openai.com/v1/chat/completions"
LLM_MODEL = "gpt-4o"
SEARCH_ENDPOINT = "https://api.search.brave.com/res/v1/web/search"
TOKEN_GITHUB = ""

[[queues.consumers]]
queue = "my-queue"