name = "similarity_search"
main = "src/index.ts"
compatibility_date = "2023-12-01"
compatibility_flags = ["nodejs_compat"]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
name = "similarity-search"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
VECTORIZE_INDEX = "similarity-index"
AI_MODEL = "@cf/baai/bge-base-en-v1.5"

[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "similarity-index"
# binding = "AI"