name = "worker-article-receiver"
main = "src/worker.js"
compatibility_date = "2024-04-22"
workers_dev = true

kv_namespaces = [
  { binding = "checkerPrompts", id = "" }
]

services = [
  { binding = "WORKER_ARTICLE_RAG", service = "worker-article-rag", environment = "production" }
]

[[queues.producers]]
queue = "my-queue"
binding = "MY_QUEUE"

[vars]
OPENAI_API_KEY = ""
BRAVE_API_KEY = ""
TOKEN_GITHUB = ""
LLM_ENDPOINT = "https://api.openai.com/v1/chat/completions" #recommend to use https://developers.cloudflare.com/ai-gateway/
LLM_MODEL = "gpt-4o"