on:
  pull_request:
    types:
      # - opened
      # - reopened
      - ready_for_review
      - review_requested
 
    paths:
      - "content/**/*.md"

jobs:
  fact-check:
    runs-on: ubuntu-latest
    name: "Verify statements in content diff for truthness"

    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry
      
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      - name: Install Python dependencies
        run: poetry install

      - name: Run fact-checking script
        run: | 
          poetry run python fact-check.py \
            --repo-url "${{ github.event.pull_request.head.repo.clone_url }}" \
            --pull-request-head "${{ github.event.pull_request.head.ref }}" \
            --pull-request-base "${{ github.event.pull_request.base.ref }}" \
            --pull-request-number "${{ github.event.pull_request.number }}" \
            --github-token "${{ secrets.GITHUB_TOKEN }}" \
            --openai-key "${{ secrets.OPENAI_KEY }}" \
            --content-path "content"
