on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: read
  pull-requests: write

jobs:
  
  plagiarism-check:
    runs-on: ubuntu-latest
    name: "Checks a new article from a PR for plagiarism"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Go to PR files
        run: gh pr checkout "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Save article locally
        id: pr-files
        run: |
          pr_number="${{ github.event.issue.number }}"
          file_path="$(gh pr diff --name-only $pr_number | grep '\.md' | head -n 1)"
          if [ -n "$file_path" ]; then
            cat "$file_path" > article.txt
          else
            echo "No .md file found in the PR." > article.txt
          fi
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Check for plagiarism
        id: plagiarism-check
        run: |
          content="$(cat article.txt)"
          escaped_content=$(jq -Rs . <<<"$content")
          result="$(curl -X POST "${{ secrets.WORKER_URL }}" -H "Content-Type: application/json" -d "{\"text\": $escaped_content}")"

          echo "$result" > results.txt

      - name: Format and post response
        run: |
          response="$(cat results.txt)"
          formatted_response="## Plagiarism Check Results:
          "

          plagiarismPercent=$(echo "$response" | jq -r '.plagiarismPercent')
          formatted_response+="### $plagiarismPercent% plagiarism detected 
          "

          results=$(echo "$response" | jq -r '.results')
          if [ "$results" != "None" ]; then
            while IFS= read -r result; do
              sentence=$(echo "$result" | jq -r '.sentence')
              formatted_response+=" Sentence: $sentence
              "
              matches=$(echo "$result" | jq -c '.matches')
              while IFS= read -r match; do
                title=$(echo "$match" | jq -r '.title')
                link=$(echo "$match" | jq -r '.link')
                formatted_response+="[$title]($link)
                "
              done <<< "$(echo "$matches" | jq -c '.[]')"
            done <<< "$(echo "$results" | jq -c '.[]')"
          else
            formatted_response+="### No plagiarism detected."
          fi

          gh pr comment "${{ github.event.issue.number }}" --body "$formatted_response"

        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"